// Generated by database/scripts/gen-starter-terms.mjs from
// database/crates/lbb-ontology/starters/<id>.json. Do not edit: run
// database/scripts/gen-clients.sh.
//
// The ontology starters' terms, with the IRIs SPARQL uses for them:
// `starters.crm.classes.Organization.iri`.

/** A class of a starter. */
export interface StarterClassTerm {
  readonly name: string;
  /** The class IRI, for example in `?org a <…>`. */
  readonly iri: string;
  /** Direct parents, by name. */
  readonly superTypes: readonly string[];
}

/** A property of a starter. Properties are global: one value type each. */
export interface StarterPropertyTerm {
  readonly name: string;
  /** The predicate IRI of the property's values. */
  readonly iri: string;
  /** `bool` | `i64` | `f64` | `date_time` | `keyword` | `text` | `keyword_set` | `i64_set`. */
  readonly valueType: string;
}

/** A relation of a starter. */
export interface StarterRelationTerm {
  readonly name: string;
  /** The predicate IRI. */
  readonly iri: string;
  readonly domain: readonly string[];
  readonly range: readonly string[];
  readonly cardinality: string;
  /** The reverse direction's name, queryable as a predicate of its own. */
  readonly inverse: string | null;
  readonly inverseIri: string | null;
}

/** A question the starter's ontology answers. */
export interface StarterQuestion {
  readonly id: string;
  readonly text: string;
  /** The SPARQL that answers it, when one exists. */
  readonly sparql: string | null;
}

/** The terms of one starter, keyed by name. */
export interface StarterTerms {
  readonly id: string;
  readonly version: string;
  readonly label: string;
  readonly classes: Readonly<Record<string, StarterClassTerm>>;
  readonly properties: Readonly<Record<string, StarterPropertyTerm>>;
  readonly relations: Readonly<Record<string, StarterRelationTerm>>;
  readonly questions: readonly StarterQuestion[];
}

/** The CRM starter 1.1.0. */
export const crm = {
  id: "crm",
  version: "1.1.0",
  label: "CRM",
  classes: {
    Party: {
      name: "Party",
      iri: "https://littlebigbrain.com/class/party",
      superTypes: [],
    },
    Organization: {
      name: "Organization",
      iri: "https://littlebigbrain.com/class/organization",
      superTypes: ["Party"],
    },
    Person: {
      name: "Person",
      iri: "https://littlebigbrain.com/class/person",
      superTypes: ["Party"],
    },
    User: {
      name: "User",
      iri: "https://littlebigbrain.com/class/user",
      superTypes: ["Person"],
    },
    Team: {
      name: "Team",
      iri: "https://littlebigbrain.com/class/team",
      superTypes: [],
    },
    Task: {
      name: "Task",
      iri: "https://littlebigbrain.com/class/task",
      superTypes: [],
    },
    Pipeline: {
      name: "Pipeline",
      iri: "https://littlebigbrain.com/class/pipeline",
      superTypes: [],
    },
    Stage: {
      name: "Stage",
      iri: "https://littlebigbrain.com/class/stage",
      superTypes: [],
    },
    Lead: {
      name: "Lead",
      iri: "https://littlebigbrain.com/class/lead",
      superTypes: ["Party"],
    },
    Deal: {
      name: "Deal",
      iri: "https://littlebigbrain.com/class/deal",
      superTypes: [],
    },
    Ticket: {
      name: "Ticket",
      iri: "https://littlebigbrain.com/class/ticket",
      superTypes: [],
    },
    Activity: {
      name: "Activity",
      iri: "https://littlebigbrain.com/class/activity",
      superTypes: [],
    },
    Call: {
      name: "Call",
      iri: "https://littlebigbrain.com/class/call",
      superTypes: ["Activity"],
    },
    Email: {
      name: "Email",
      iri: "https://littlebigbrain.com/class/email",
      superTypes: ["Activity"],
    },
    Meeting: {
      name: "Meeting",
      iri: "https://littlebigbrain.com/class/meeting",
      superTypes: ["Activity"],
    },
    Note: {
      name: "Note",
      iri: "https://littlebigbrain.com/class/note",
      superTypes: ["Activity"],
    },
    Product: {
      name: "Product",
      iri: "https://littlebigbrain.com/class/product",
      superTypes: [],
    },
    LineItem: {
      name: "LineItem",
      iri: "https://littlebigbrain.com/class/lineitem",
      superTypes: [],
    },
    Quote: {
      name: "Quote",
      iri: "https://littlebigbrain.com/class/quote",
      superTypes: [],
    },
    Campaign: {
      name: "Campaign",
      iri: "https://littlebigbrain.com/class/campaign",
      superTypes: [],
    },
  },
  properties: {
    source_system: {
      name: "source_system",
      iri: "https://littlebigbrain.com/p/source_system",
      valueType: "keyword",
    },
    source_id: {
      name: "source_id",
      iri: "https://littlebigbrain.com/p/source_id",
      valueType: "keyword",
    },
    source_url: {
      name: "source_url",
      iri: "https://littlebigbrain.com/p/source_url",
      valueType: "keyword",
    },
    source_updated_at: {
      name: "source_updated_at",
      iri: "https://littlebigbrain.com/p/source_updated_at",
      valueType: "date_time",
    },
    source_key: {
      name: "source_key",
      iri: "https://littlebigbrain.com/p/source_key",
      valueType: "keyword",
    },
    text: {
      name: "text",
      iri: "https://littlebigbrain.com/p/text",
      valueType: "text",
    },
    acl: {
      name: "acl",
      iri: "https://littlebigbrain.com/p/acl",
      valueType: "keyword_set",
    },
    created_at: {
      name: "created_at",
      iri: "https://littlebigbrain.com/p/created_at",
      valueType: "date_time",
    },
    modified_at: {
      name: "modified_at",
      iri: "https://littlebigbrain.com/p/modified_at",
      valueType: "date_time",
    },
    description: {
      name: "description",
      iri: "https://littlebigbrain.com/p/description",
      valueType: "text",
    },
    phone: {
      name: "phone",
      iri: "https://littlebigbrain.com/p/phone",
      valueType: "keyword",
    },
    website: {
      name: "website",
      iri: "https://littlebigbrain.com/p/website",
      valueType: "keyword",
    },
    street_address: {
      name: "street_address",
      iri: "https://littlebigbrain.com/p/street_address",
      valueType: "keyword",
    },
    city: {
      name: "city",
      iri: "https://littlebigbrain.com/p/city",
      valueType: "keyword",
    },
    region: {
      name: "region",
      iri: "https://littlebigbrain.com/p/region",
      valueType: "keyword",
    },
    postal_code: {
      name: "postal_code",
      iri: "https://littlebigbrain.com/p/postal_code",
      valueType: "keyword",
    },
    country: {
      name: "country",
      iri: "https://littlebigbrain.com/p/country",
      valueType: "keyword",
    },
    linkedin_url: {
      name: "linkedin_url",
      iri: "https://littlebigbrain.com/p/linkedin_url",
      valueType: "keyword",
    },
    lifecycle_stage: {
      name: "lifecycle_stage",
      iri: "https://littlebigbrain.com/p/lifecycle_stage",
      valueType: "keyword",
    },
    domain: {
      name: "domain",
      iri: "https://littlebigbrain.com/p/domain",
      valueType: "keyword",
    },
    industry: {
      name: "industry",
      iri: "https://littlebigbrain.com/p/industry",
      valueType: "keyword",
    },
    annual_revenue: {
      name: "annual_revenue",
      iri: "https://littlebigbrain.com/p/annual_revenue",
      valueType: "f64",
    },
    employee_count: {
      name: "employee_count",
      iri: "https://littlebigbrain.com/p/employee_count",
      valueType: "i64",
    },
    company_type: {
      name: "company_type",
      iri: "https://littlebigbrain.com/p/company_type",
      valueType: "keyword",
    },
    first_name: {
      name: "first_name",
      iri: "https://littlebigbrain.com/p/first_name",
      valueType: "keyword",
    },
    last_name: {
      name: "last_name",
      iri: "https://littlebigbrain.com/p/last_name",
      valueType: "keyword",
    },
    email: {
      name: "email",
      iri: "https://littlebigbrain.com/p/email",
      valueType: "keyword",
    },
    job_title: {
      name: "job_title",
      iri: "https://littlebigbrain.com/p/job_title",
      valueType: "keyword",
    },
    mobile_phone: {
      name: "mobile_phone",
      iri: "https://littlebigbrain.com/p/mobile_phone",
      valueType: "keyword",
    },
    company_name: {
      name: "company_name",
      iri: "https://littlebigbrain.com/p/company_name",
      valueType: "keyword",
    },
    lead_status: {
      name: "lead_status",
      iri: "https://littlebigbrain.com/p/lead_status",
      valueType: "keyword",
    },
    lead_source: {
      name: "lead_source",
      iri: "https://littlebigbrain.com/p/lead_source",
      valueType: "keyword",
    },
    is_active: {
      name: "is_active",
      iri: "https://littlebigbrain.com/p/is_active",
      valueType: "bool",
    },
    source_user_id: {
      name: "source_user_id",
      iri: "https://littlebigbrain.com/p/source_user_id",
      valueType: "keyword",
    },
    amount: {
      name: "amount",
      iri: "https://littlebigbrain.com/p/amount",
      valueType: "f64",
    },
    currency: {
      name: "currency",
      iri: "https://littlebigbrain.com/p/currency",
      valueType: "keyword",
    },
    unit_price: {
      name: "unit_price",
      iri: "https://littlebigbrain.com/p/unit_price",
      valueType: "f64",
    },
    quantity: {
      name: "quantity",
      iri: "https://littlebigbrain.com/p/quantity",
      valueType: "f64",
    },
    discount: {
      name: "discount",
      iri: "https://littlebigbrain.com/p/discount",
      valueType: "f64",
    },
    budget: {
      name: "budget",
      iri: "https://littlebigbrain.com/p/budget",
      valueType: "f64",
    },
    close_date: {
      name: "close_date",
      iri: "https://littlebigbrain.com/p/close_date",
      valueType: "date_time",
    },
    probability: {
      name: "probability",
      iri: "https://littlebigbrain.com/p/probability",
      valueType: "f64",
    },
    deal_type: {
      name: "deal_type",
      iri: "https://littlebigbrain.com/p/deal_type",
      valueType: "keyword",
    },
    forecast_category: {
      name: "forecast_category",
      iri: "https://littlebigbrain.com/p/forecast_category",
      valueType: "keyword",
    },
    is_closed: {
      name: "is_closed",
      iri: "https://littlebigbrain.com/p/is_closed",
      valueType: "bool",
    },
    is_won: {
      name: "is_won",
      iri: "https://littlebigbrain.com/p/is_won",
      valueType: "bool",
    },
    won_reason: {
      name: "won_reason",
      iri: "https://littlebigbrain.com/p/won_reason",
      valueType: "text",
    },
    lost_reason: {
      name: "lost_reason",
      iri: "https://littlebigbrain.com/p/lost_reason",
      valueType: "text",
    },
    next_step: {
      name: "next_step",
      iri: "https://littlebigbrain.com/p/next_step",
      valueType: "text",
    },
    object_type: {
      name: "object_type",
      iri: "https://littlebigbrain.com/p/object_type",
      valueType: "keyword",
    },
    display_order: {
      name: "display_order",
      iri: "https://littlebigbrain.com/p/display_order",
      valueType: "i64",
    },
    stage_category: {
      name: "stage_category",
      iri: "https://littlebigbrain.com/p/stage_category",
      valueType: "keyword",
    },
    priority: {
      name: "priority",
      iri: "https://littlebigbrain.com/p/priority",
      valueType: "keyword",
    },
    category: {
      name: "category",
      iri: "https://littlebigbrain.com/p/category",
      valueType: "keyword",
    },
    channel: {
      name: "channel",
      iri: "https://littlebigbrain.com/p/channel",
      valueType: "keyword",
    },
    closed_at: {
      name: "closed_at",
      iri: "https://littlebigbrain.com/p/closed_at",
      valueType: "date_time",
    },
    occurred_at: {
      name: "occurred_at",
      iri: "https://littlebigbrain.com/p/occurred_at",
      valueType: "date_time",
    },
    direction: {
      name: "direction",
      iri: "https://littlebigbrain.com/p/direction",
      valueType: "keyword",
    },
    duration_seconds: {
      name: "duration_seconds",
      iri: "https://littlebigbrain.com/p/duration_seconds",
      valueType: "i64",
    },
    status: {
      name: "status",
      iri: "https://littlebigbrain.com/p/status",
      valueType: "keyword",
    },
    outcome: {
      name: "outcome",
      iri: "https://littlebigbrain.com/p/outcome",
      valueType: "keyword",
    },
    from_address: {
      name: "from_address",
      iri: "https://littlebigbrain.com/p/from_address",
      valueType: "keyword",
    },
    to_addresses: {
      name: "to_addresses",
      iri: "https://littlebigbrain.com/p/to_addresses",
      valueType: "keyword_set",
    },
    start_at: {
      name: "start_at",
      iri: "https://littlebigbrain.com/p/start_at",
      valueType: "date_time",
    },
    end_at: {
      name: "end_at",
      iri: "https://littlebigbrain.com/p/end_at",
      valueType: "date_time",
    },
    location: {
      name: "location",
      iri: "https://littlebigbrain.com/p/location",
      valueType: "keyword",
    },
    due_at: {
      name: "due_at",
      iri: "https://littlebigbrain.com/p/due_at",
      valueType: "date_time",
    },
    completed_at: {
      name: "completed_at",
      iri: "https://littlebigbrain.com/p/completed_at",
      valueType: "date_time",
    },
    sku: {
      name: "sku",
      iri: "https://littlebigbrain.com/p/sku",
      valueType: "keyword",
    },
    expires_at: {
      name: "expires_at",
      iri: "https://littlebigbrain.com/p/expires_at",
      valueType: "date_time",
    },
    campaign_type: {
      name: "campaign_type",
      iri: "https://littlebigbrain.com/p/campaign_type",
      valueType: "keyword",
    },
  },
  relations: {
    WORKS_AT: {
      name: "WORKS_AT",
      iri: "https://littlebigbrain.com/r/works_at",
      domain: ["Person"],
      range: ["Organization"],
      cardinality: "many_to_many",
      inverse: "EMPLOYS",
      inverseIri: "https://littlebigbrain.com/r/employs",
    },
    REPORTS_TO: {
      name: "REPORTS_TO",
      iri: "https://littlebigbrain.com/r/reports_to",
      domain: ["Person"],
      range: ["Person"],
      cardinality: "many_to_one",
      inverse: "MANAGES",
      inverseIri: "https://littlebigbrain.com/r/manages",
    },
    SUBSIDIARY_OF: {
      name: "SUBSIDIARY_OF",
      iri: "https://littlebigbrain.com/r/subsidiary_of",
      domain: ["Organization"],
      range: ["Organization"],
      cardinality: "many_to_one",
      inverse: "HAS_SUBSIDIARY",
      inverseIri: "https://littlebigbrain.com/r/has_subsidiary",
    },
    OWNED_BY: {
      name: "OWNED_BY",
      iri: "https://littlebigbrain.com/r/owned_by",
      domain: ["Party", "Deal", "Ticket", "Activity"],
      range: ["User"],
      cardinality: "many_to_one",
      inverse: "OWNS",
      inverseIri: "https://littlebigbrain.com/r/owns",
    },
    ASSIGNED_TO: {
      name: "ASSIGNED_TO",
      iri: "https://littlebigbrain.com/r/assigned_to",
      domain: ["Task"],
      range: ["User"],
      cardinality: "many_to_one",
      inverse: "ASSIGNEE_OF",
      inverseIri: "https://littlebigbrain.com/r/assignee_of",
    },
    MEMBER_OF: {
      name: "MEMBER_OF",
      iri: "https://littlebigbrain.com/r/member_of",
      domain: ["User"],
      range: ["Team"],
      cardinality: "many_to_many",
      inverse: "HAS_MEMBER",
      inverseIri: "https://littlebigbrain.com/r/has_member",
    },
    FOR_ORGANIZATION: {
      name: "FOR_ORGANIZATION",
      iri: "https://littlebigbrain.com/r/for_organization",
      domain: ["Deal", "Ticket", "Quote"],
      range: ["Organization"],
      cardinality: "many_to_many",
      inverse: "ORGANIZATION_OF",
      inverseIri: "https://littlebigbrain.com/r/organization_of",
    },
    INVOLVES: {
      name: "INVOLVES",
      iri: "https://littlebigbrain.com/r/involves",
      domain: ["Deal", "Ticket"],
      range: ["Person"],
      cardinality: "many_to_many",
      inverse: "INVOLVED_IN",
      inverseIri: "https://littlebigbrain.com/r/involved_in",
    },
    ABOUT: {
      name: "ABOUT",
      iri: "https://littlebigbrain.com/r/about",
      domain: ["Activity", "Task"],
      range: ["Party", "Deal", "Ticket"],
      cardinality: "many_to_many",
      inverse: "HAS_ACTIVITY",
      inverseIri: "https://littlebigbrain.com/r/has_activity",
    },
    IN_STAGE: {
      name: "IN_STAGE",
      iri: "https://littlebigbrain.com/r/in_stage",
      domain: ["Deal", "Ticket"],
      range: ["Stage"],
      cardinality: "many_to_one",
      inverse: "STAGE_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/stage_holds",
    },
    IN_PIPELINE: {
      name: "IN_PIPELINE",
      iri: "https://littlebigbrain.com/r/in_pipeline",
      domain: ["Stage"],
      range: ["Pipeline"],
      cardinality: "many_to_one",
      inverse: "PIPELINE_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/pipeline_holds",
    },
    HAS_LINE_ITEM: {
      name: "HAS_LINE_ITEM",
      iri: "https://littlebigbrain.com/r/has_line_item",
      domain: ["Deal", "Quote"],
      range: ["LineItem"],
      cardinality: "many_to_many",
      inverse: "LINE_ITEM_OF",
      inverseIri: "https://littlebigbrain.com/r/line_item_of",
    },
    FOR_PRODUCT: {
      name: "FOR_PRODUCT",
      iri: "https://littlebigbrain.com/r/for_product",
      domain: ["LineItem"],
      range: ["Product"],
      cardinality: "many_to_one",
      inverse: "SOLD_AS",
      inverseIri: "https://littlebigbrain.com/r/sold_as",
    },
    QUOTE_FOR: {
      name: "QUOTE_FOR",
      iri: "https://littlebigbrain.com/r/quote_for",
      domain: ["Quote"],
      range: ["Deal"],
      cardinality: "many_to_one",
      inverse: "HAS_QUOTE",
      inverseIri: "https://littlebigbrain.com/r/has_quote",
    },
    IN_CAMPAIGN: {
      name: "IN_CAMPAIGN",
      iri: "https://littlebigbrain.com/r/in_campaign",
      domain: ["Person", "Lead"],
      range: ["Campaign"],
      cardinality: "many_to_many",
      inverse: "HAS_CAMPAIGN_MEMBER",
      inverseIri: "https://littlebigbrain.com/r/has_campaign_member",
    },
    CONVERTED_TO: {
      name: "CONVERTED_TO",
      iri: "https://littlebigbrain.com/r/converted_to",
      domain: ["Lead"],
      range: ["Person", "Organization", "Deal"],
      cardinality: "many_to_many",
      inverse: "CONVERTED_FROM",
      inverseIri: "https://littlebigbrain.com/r/converted_from",
    },
  },
  questions: [
    {
      id: "crm-01",
      text: "Which organizations does a person work at, and with what job title?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?organization ?job_title WHERE {\n  # Input: a person's name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person ;\n     r:works_at ?o .\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?person ?organization\n",
    },
    {
      id: "crm-02",
      text: "Which deals are open for an organization, with their amount and stage?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?deal ?amount ?currency ?stage WHERE {\n  # Input: an organization's name. UNDEF answers for every organization.\n  VALUES ?organization { UNDEF }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  ?d a/rdfs:subClassOf* c:deal ;\n     r:for_organization ?o ;\n     p:is_closed false ;\n     rdfs:label ?deal .\n  OPTIONAL { ?d p:amount ?amount }\n  OPTIONAL { ?d p:currency ?currency }\n  OPTIONAL { ?d r:in_stage ?s . ?s a/rdfs:subClassOf* c:stage ; rdfs:label ?stage }\n}\nORDER BY ?organization DESC(?amount)\n",
    },
    {
      id: "crm-03",
      text: "What is the open pipeline amount per pipeline and stage, in stage order?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?pipeline ?stage ?currency (COUNT(?d) AS ?deals) (SUM(?amount) AS ?open_amount) WHERE {\n  ?d a/rdfs:subClassOf* c:deal ;\n     p:is_closed false ;\n     p:amount ?amount ;\n     r:in_stage ?s .\n  OPTIONAL { ?d p:currency ?currency }\n  ?s a/rdfs:subClassOf* c:stage ;\n     rdfs:label ?stage ;\n     p:display_order ?order ;\n     r:in_pipeline ?pl .\n  ?pl a/rdfs:subClassOf* c:pipeline ;\n      rdfs:label ?pipeline .\n}\nGROUP BY ?pipeline ?stage ?order ?currency\nORDER BY ?pipeline ?order ?currency\n",
    },
    {
      id: "crm-04",
      text: "Which deals are expected to close this quarter, and who owns them?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?close_date ?amount ?currency ?owner WHERE {\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     p:is_closed false ;\n     p:close_date ?close_date .\n  # This quarter: the year and the quarter of today.\n  FILTER(YEAR(?close_date) = YEAR(NOW())\n         && CEIL(MONTH(?close_date) / 3) = CEIL(MONTH(NOW()) / 3))\n  OPTIONAL { ?d p:amount ?amount }\n  OPTIONAL { ?d p:currency ?currency }\n  OPTIONAL { ?d r:owned_by ?u . ?u a/rdfs:subClassOf* c:user ; rdfs:label ?owner }\n}\nORDER BY ?close_date\n",
    },
    {
      id: "crm-05",
      text: "Which deals were won or lost in a period, and why were the lost ones lost?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?deal ?close_date ?won ?lost_reason WHERE {\n  # Inputs: the period's first instant and the instant after it, as\n  # xsd:dateTime. UNDEF leaves that end open.\n  VALUES (?from ?to) { (UNDEF UNDEF) }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     p:is_closed true ;\n     p:is_won ?won ;\n     p:close_date ?close_date .\n  FILTER(!BOUND(?from) || ?close_date >= ?from)\n  FILTER(!BOUND(?to) || ?close_date < ?to)\n  OPTIONAL { ?d p:lost_reason ?lost_reason }\n}\nORDER BY ?close_date\n",
    },
    {
      id: "crm-06",
      text: "Who are the people involved in a deal, and what are their job titles?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?person ?job_title WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     r:involves ?x .\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?deal ?person\n",
    },
    {
      id: "crm-07",
      text: "What calls, emails and meetings happened with an organization in the last 30 days?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?organization ?activity ?kind ?occurred_at WHERE {\n  # Inputs: an organization\'s name, and the start of the window (30 days\n  # ago) as xsd:dateTime. UNDEF answers for every organization or date.\n  VALUES (?organization ?since) { (UNDEF UNDEF) }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  ?a a/rdfs:subClassOf* c:activity ;\n     r:about ?o ;\n     rdfs:label ?activity ;\n     p:occurred_at ?occurred_at ;\n     a ?type .\n  VALUES (?type ?kind) { (c:call "call") (c:email "email") (c:meeting "meeting") }\n  FILTER(!BOUND(?since) || ?occurred_at >= ?since)\n  FILTER(?occurred_at <= NOW())\n}\nORDER BY ?organization DESC(?occurred_at)\n',
    },
    {
      id: "crm-08",
      text: "When was the last activity with a person, and what kind was it?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?activity ?kind ?occurred_at WHERE {\n  # Input: a person\'s name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  {\n    SELECT ?x (MAX(?at) AS ?occurred_at) WHERE {\n      ?any a/rdfs:subClassOf* c:activity ;\n           r:about ?x ;\n           p:occurred_at ?at .\n      FILTER(?at <= NOW())\n    }\n    GROUP BY ?x\n  }\n  ?a a/rdfs:subClassOf* c:activity ;\n     r:about ?x ;\n     p:occurred_at ?occurred_at ;\n     rdfs:label ?activity ;\n     a ?type .\n  ?type rdfs:subClassOf+ c:activity .\n  BIND(STRAFTER(STR(?type), "/class/") AS ?kind)\n}\nORDER BY ?person\n',
    },
    {
      id: "crm-09",
      text: "Which open tickets does an organization have, by priority and stage?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?ticket ?priority ?stage WHERE {\n  # Input: an organization's name. UNDEF answers for every organization.\n  VALUES ?organization { UNDEF }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  ?t a/rdfs:subClassOf* c:ticket ;\n     r:for_organization ?o ;\n     p:is_closed false ;\n     rdfs:label ?ticket .\n  OPTIONAL { ?t p:priority ?priority }\n  OPTIONAL { ?t r:in_stage ?s . ?s a/rdfs:subClassOf* c:stage ; rdfs:label ?stage }\n}\nORDER BY ?organization ?priority ?stage\n",
    },
    {
      id: "crm-10",
      text: "Which users own the most open deals and tickets?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?owner (COUNT(?record) AS ?open_records) WHERE {\n  { ?record a/rdfs:subClassOf* c:deal } UNION { ?record a/rdfs:subClassOf* c:ticket }\n  ?record p:is_closed false ;\n          r:owned_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?owner .\n}\nGROUP BY ?owner\nORDER BY DESC(?open_records) ?owner\n",
    },
    {
      id: "crm-11",
      text: "Which teams does a user belong to, and is the user active?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?user ?is_active ?team WHERE {\n  # Input: a user's name. UNDEF answers for every user.\n  VALUES ?user { UNDEF }\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  OPTIONAL { ?u p:is_active ?is_active }\n  OPTIONAL { ?u r:member_of ?t . ?t a/rdfs:subClassOf* c:team ; rdfs:label ?team }\n}\nORDER BY ?user ?team\n",
    },
    {
      id: "crm-12",
      text: "Which products does a deal sell, with quantity and price?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?product ?sku ?quantity ?unit_price ?amount WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     r:has_line_item ?line .\n  ?line a/rdfs:subClassOf* c:lineitem .\n  OPTIONAL { ?line p:quantity ?quantity }\n  OPTIONAL { ?line p:unit_price ?unit_price }\n  OPTIONAL { ?line p:amount ?amount }\n  OPTIONAL {\n    ?line r:for_product ?pr .\n    ?pr a/rdfs:subClassOf* c:product ;\n        rdfs:label ?product .\n    OPTIONAL { ?pr p:sku ?sku }\n  }\n}\nORDER BY ?deal ?product\n",
    },
    {
      id: "crm-13",
      text: "Which quotes exist for a deal, and when do they expire?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?quote ?status ?amount ?currency ?expires_at WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal .\n  ?q a/rdfs:subClassOf* c:quote ;\n     r:quote_for ?d ;\n     rdfs:label ?quote .\n  OPTIONAL { ?q p:status ?status }\n  OPTIONAL { ?q p:amount ?amount }\n  OPTIONAL { ?q p:currency ?currency }\n  OPTIONAL { ?q p:expires_at ?expires_at }\n}\nORDER BY ?deal ?expires_at\n",
    },
    {
      id: "crm-14",
      text: "Which organizations belong to a parent organization, directly or indirectly?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?parent ?organization ?domain ?direct_parent WHERE {\n  # Input: the parent organization's name. UNDEF answers for every parent.\n  VALUES ?parent { UNDEF }\n  ?top a/rdfs:subClassOf* c:organization ;\n       rdfs:label ?parent .\n  # Directly or indirectly: one or more SUBSIDIARY_OF steps.\n  ?o r:subsidiary_of+ ?top ;\n     rdfs:label ?organization ;\n     r:subsidiary_of ?up .\n  ?up rdfs:label ?direct_parent .\n  OPTIONAL { ?o p:domain ?domain }\n}\nORDER BY ?parent ?organization\n",
    },
    {
      id: "crm-15",
      text: "Which leads came from a campaign, and which of them converted to deals?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?campaign ?campaign_start ?lead ?lead_source ?converted_deal WHERE {\n  # Input: a campaign's name. UNDEF answers for every campaign.\n  VALUES ?campaign { UNDEF }\n  ?k a/rdfs:subClassOf* c:campaign ;\n     rdfs:label ?campaign .\n  OPTIONAL { ?k p:start_at ?campaign_start }\n  ?l a/rdfs:subClassOf* c:lead ;\n     r:in_campaign ?k ;\n     rdfs:label ?lead .\n  OPTIONAL { ?l p:lead_source ?lead_source }\n  OPTIONAL {\n    ?l r:converted_to ?d .\n    ?d a/rdfs:subClassOf* c:deal ;\n       rdfs:label ?converted_deal .\n  }\n}\nORDER BY ?campaign ?lead\n",
    },
    {
      id: "crm-16",
      text: "Who reports to a given person?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?manager ?person ?job_title WHERE {\n  # Input: the manager's name. UNDEF answers for every manager.\n  VALUES ?manager { UNDEF }\n  ?m a/rdfs:subClassOf* c:person ;\n     rdfs:label ?manager .\n  ?x r:reports_to ?m ;\n     rdfs:label ?person .\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?manager ?person\n",
    },
    {
      id: "crm-17",
      text: "Which organizations are in an industry and country, with their size and revenue?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?industry ?country ?employee_count ?annual_revenue WHERE {\n  # Inputs: an industry and a country. UNDEF answers for every industry or\n  # country.\n  VALUES (?industry ?country) { (UNDEF UNDEF) }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization ;\n     p:industry ?industry ;\n     p:country ?country .\n  OPTIONAL { ?o p:employee_count ?employee_count }\n  OPTIONAL { ?o p:annual_revenue ?annual_revenue }\n}\nORDER BY DESC(?annual_revenue)\n",
    },
    {
      id: "crm-18",
      text: "What lifecycle stage and lead status does an organization or person have?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?party ?kind ?lifecycle_stage ?lead_status WHERE {\n  # Input: the name of an organization or a person. UNDEF answers for every\n  # one.\n  VALUES ?party { UNDEF }\n  ?x a/rdfs:subClassOf* c:party ;\n     rdfs:label ?party .\n  { ?x a/rdfs:subClassOf* c:organization BIND("organization" AS ?kind) }\n  UNION\n  { ?x a/rdfs:subClassOf* c:person BIND("person" AS ?kind) }\n  OPTIONAL { ?x p:lifecycle_stage ?lifecycle_stage }\n  OPTIONAL { ?x p:lead_status ?lead_status }\n}\nORDER BY ?kind ?party\n',
    },
    {
      id: "crm-19",
      text: "Which open deals have had no activity in 30 days?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?deal ?owner WHERE {\n  # Input: the start of the window (30 days ago) as xsd:dateTime. UNDEF\n  # finds the open deals with no activity at all.\n  VALUES ?since { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal ;\n     p:is_closed false .\n  FILTER NOT EXISTS {\n    ?a a/rdfs:subClassOf* c:activity ;\n       r:about ?d ;\n       p:occurred_at ?at .\n    FILTER(!BOUND(?since) || ?at >= ?since)\n  }\n  OPTIONAL { ?d r:owned_by ?u . ?u rdfs:label ?owner }\n}\nORDER BY ?deal\n",
    },
    {
      id: "crm-20",
      text: "Which tasks are overdue, on which records, and who does them?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?status ?due_at ?record ?assignee WHERE {\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task ;\n     p:due_at ?due_at .\n  # Overdue: due before now and not done.\n  FILTER(?due_at < NOW())\n  FILTER NOT EXISTS { ?t p:completed_at ?completed_at }\n  OPTIONAL { ?t p:status ?status }\n  OPTIONAL { ?t r:about ?x . ?x rdfs:label ?record }\n  OPTIONAL { ?t r:assigned_to ?u . ?u rdfs:label ?assignee }\n}\nORDER BY ?due_at\n",
    },
    {
      id: "crm-21",
      text: "Which meetings are set for next week, and with whom?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?meeting ?start_at ?end_at ?location ?person WHERE {\n  # Inputs: the window's first instant and the instant after it, as\n  # xsd:dateTime (next Monday and the Monday after). UNDEF reads from now on.\n  VALUES (?from ?to) { (UNDEF UNDEF) }\n  ?m a/rdfs:subClassOf* c:meeting ;\n     rdfs:label ?meeting ;\n     p:start_at ?start_at .\n  FILTER(?start_at >= COALESCE(?from, NOW()))\n  FILTER(!BOUND(?to) || ?start_at < ?to)\n  OPTIONAL { ?m p:end_at ?end_at }\n  OPTIONAL { ?m p:location ?location }\n  OPTIONAL { ?m r:about ?x . ?x a/rdfs:subClassOf* c:person ; rdfs:label ?person }\n}\nORDER BY ?start_at ?person\n",
    },
    {
      id: "crm-22",
      text: "What is each owner's win rate: won deals out of closed deals?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?owner (SUM(IF(?won, 1, 0)) AS ?won_deals) (COUNT(?d) AS ?closed_deals)\n       (SUM(IF(?won, 1, 0)) / COUNT(?d) AS ?win_rate) WHERE {\n  ?d a/rdfs:subClassOf* c:deal ;\n     p:is_closed true ;\n     p:is_won ?won ;\n     r:owned_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?owner .\n}\nGROUP BY ?owner\nORDER BY DESC(?win_rate) ?owner\n",
    },
    {
      id: "crm-23",
      text: "Which tickets involve a person, and through which channel did they come in?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?ticket ?channel ?created_at WHERE {\n  # Input: a person's name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  ?t a/rdfs:subClassOf* c:ticket ;\n     r:involves ?x ;\n     rdfs:label ?ticket .\n  OPTIONAL { ?t p:channel ?channel }\n  OPTIONAL { ?t p:created_at ?created_at }\n}\nORDER BY ?person ?created_at\n",
    },
    {
      id: "crm-24",
      text: "Which organizations have both open tickets and open deals?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization WHERE {\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization .\n  FILTER EXISTS {\n    ?t a/rdfs:subClassOf* c:ticket ; r:for_organization ?o ; p:is_closed false .\n  }\n  FILTER EXISTS {\n    ?d a/rdfs:subClassOf* c:deal ; r:for_organization ?o ; p:is_closed false .\n  }\n}\nORDER BY ?organization\n",
    },
    {
      id: "crm-25",
      text: "Where does a record come from: which system, which id, which link?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?record ?kind ?source_system ?source_id ?source_url ?source_updated_at WHERE {\n  # Input: a record\'s name. UNDEF answers for every organization and person.\n  VALUES ?record { UNDEF }\n  { ?x a/rdfs:subClassOf* c:organization BIND("organization" AS ?kind) }\n  UNION\n  { ?x a/rdfs:subClassOf* c:person BIND("person" AS ?kind) }\n  ?x rdfs:label ?record ;\n     p:source_system ?source_system .\n  OPTIONAL { ?x p:source_id ?source_id }\n  OPTIONAL { ?x p:source_url ?source_url }\n  OPTIONAL { ?x p:source_updated_at ?source_updated_at }\n}\nORDER BY ?kind ?record\n',
    },
    {
      id: "crm-26",
      text: "Which notes were written on a deal, and when?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?deal ?note ?created_at ?text WHERE {\n  # Input: a deal's name. UNDEF answers for every deal.\n  VALUES ?deal { UNDEF }\n  ?d a/rdfs:subClassOf* c:deal ;\n     rdfs:label ?deal .\n  ?n a/rdfs:subClassOf* c:note ;\n     r:about ?d ;\n     rdfs:label ?note .\n  OPTIONAL { ?n p:created_at ?created_at }\n  OPTIONAL { ?n p:text ?text }\n}\nORDER BY ?deal DESC(?created_at)\n",
    },
    {
      id: "crm-27",
      text: "How many calls did each user make, with what outcomes and how long?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?user ?direction ?outcome (COUNT(?call) AS ?calls) (SUM(?seconds) AS ?total_seconds) WHERE {\n  ?call a/rdfs:subClassOf* c:call ;\n        r:owned_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  OPTIONAL { ?call p:direction ?direction }\n  OPTIONAL { ?call p:outcome ?outcome }\n  OPTIONAL { ?call p:duration_seconds ?seconds }\n}\nGROUP BY ?user ?direction ?outcome\nORDER BY ?user ?direction ?outcome\n",
    },
    {
      id: "crm-28",
      text: "Which emails were exchanged with a person?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?person ?email ?from_address ?to_address ?occurred_at WHERE {\n  # Input: a person's name. UNDEF answers for every person.\n  VALUES ?person { UNDEF }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  ?m a/rdfs:subClassOf* c:email ;\n     r:about ?x ;\n     rdfs:label ?email .\n  OPTIONAL { ?m p:from_address ?from_address }\n  OPTIONAL { ?m p:to_addresses ?to_address }\n  OPTIONAL { ?m p:occurred_at ?occurred_at }\n}\nORDER BY ?person DESC(?occurred_at)\n",
    },
    {
      id: "crm-29",
      text: "Which campaigns are running, with their budget and members?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?campaign ?status ?start_at ?end_at ?budget ?member WHERE {\n  ?k a/rdfs:subClassOf* c:campaign ;\n     rdfs:label ?campaign ;\n     p:start_at ?start_at ;\n     p:end_at ?end_at .\n  # Running: started and not ended.\n  FILTER(?start_at <= NOW() && ?end_at >= NOW())\n  OPTIONAL { ?k p:status ?status }\n  OPTIONAL { ?k p:budget ?budget }\n  OPTIONAL {\n    ?m r:in_campaign ?k ;\n       a/rdfs:subClassOf* c:person ;\n       rdfs:label ?member .\n  }\n}\nORDER BY ?campaign ?member\n",
    },
    {
      id: "crm-30",
      text: "What does the product catalog sell, and at what price?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?product ?sku ?unit_price ?currency WHERE {\n  ?x a/rdfs:subClassOf* c:product ;\n     rdfs:label ?product ;\n     p:is_active true .\n  OPTIONAL { ?x p:sku ?sku }\n  OPTIONAL { ?x p:unit_price ?unit_price }\n  OPTIONAL { ?x p:currency ?currency }\n}\nORDER BY ?product\n",
    },
  ],
} as const satisfies StarterTerms;

/** The Documents starter 1.1.0. */
export const documents = {
  id: "documents",
  version: "1.1.0",
  label: "Documents",
  classes: {
    Party: {
      name: "Party",
      iri: "https://littlebigbrain.com/class/party",
      superTypes: [],
    },
    Person: {
      name: "Person",
      iri: "https://littlebigbrain.com/class/person",
      superTypes: ["Party"],
    },
    User: {
      name: "User",
      iri: "https://littlebigbrain.com/class/user",
      superTypes: ["Person"],
    },
    Tag: {
      name: "Tag",
      iri: "https://littlebigbrain.com/class/tag",
      superTypes: [],
    },
    Site: {
      name: "Site",
      iri: "https://littlebigbrain.com/class/site",
      superTypes: [],
    },
    Library: {
      name: "Library",
      iri: "https://littlebigbrain.com/class/library",
      superTypes: [],
    },
    Folder: {
      name: "Folder",
      iri: "https://littlebigbrain.com/class/folder",
      superTypes: [],
    },
    Document: {
      name: "Document",
      iri: "https://littlebigbrain.com/class/document",
      superTypes: [],
    },
    Page: {
      name: "Page",
      iri: "https://littlebigbrain.com/class/page",
      superTypes: ["Document"],
    },
  },
  properties: {
    source_system: {
      name: "source_system",
      iri: "https://littlebigbrain.com/p/source_system",
      valueType: "keyword",
    },
    source_id: {
      name: "source_id",
      iri: "https://littlebigbrain.com/p/source_id",
      valueType: "keyword",
    },
    source_url: {
      name: "source_url",
      iri: "https://littlebigbrain.com/p/source_url",
      valueType: "keyword",
    },
    source_updated_at: {
      name: "source_updated_at",
      iri: "https://littlebigbrain.com/p/source_updated_at",
      valueType: "date_time",
    },
    source_key: {
      name: "source_key",
      iri: "https://littlebigbrain.com/p/source_key",
      valueType: "keyword",
    },
    text: {
      name: "text",
      iri: "https://littlebigbrain.com/p/text",
      valueType: "text",
    },
    acl: {
      name: "acl",
      iri: "https://littlebigbrain.com/p/acl",
      valueType: "keyword_set",
    },
    created_at: {
      name: "created_at",
      iri: "https://littlebigbrain.com/p/created_at",
      valueType: "date_time",
    },
    modified_at: {
      name: "modified_at",
      iri: "https://littlebigbrain.com/p/modified_at",
      valueType: "date_time",
    },
    description: {
      name: "description",
      iri: "https://littlebigbrain.com/p/description",
      valueType: "text",
    },
    phone: {
      name: "phone",
      iri: "https://littlebigbrain.com/p/phone",
      valueType: "keyword",
    },
    website: {
      name: "website",
      iri: "https://littlebigbrain.com/p/website",
      valueType: "keyword",
    },
    street_address: {
      name: "street_address",
      iri: "https://littlebigbrain.com/p/street_address",
      valueType: "keyword",
    },
    city: {
      name: "city",
      iri: "https://littlebigbrain.com/p/city",
      valueType: "keyword",
    },
    region: {
      name: "region",
      iri: "https://littlebigbrain.com/p/region",
      valueType: "keyword",
    },
    postal_code: {
      name: "postal_code",
      iri: "https://littlebigbrain.com/p/postal_code",
      valueType: "keyword",
    },
    country: {
      name: "country",
      iri: "https://littlebigbrain.com/p/country",
      valueType: "keyword",
    },
    linkedin_url: {
      name: "linkedin_url",
      iri: "https://littlebigbrain.com/p/linkedin_url",
      valueType: "keyword",
    },
    lifecycle_stage: {
      name: "lifecycle_stage",
      iri: "https://littlebigbrain.com/p/lifecycle_stage",
      valueType: "keyword",
    },
    first_name: {
      name: "first_name",
      iri: "https://littlebigbrain.com/p/first_name",
      valueType: "keyword",
    },
    last_name: {
      name: "last_name",
      iri: "https://littlebigbrain.com/p/last_name",
      valueType: "keyword",
    },
    email: {
      name: "email",
      iri: "https://littlebigbrain.com/p/email",
      valueType: "keyword",
    },
    job_title: {
      name: "job_title",
      iri: "https://littlebigbrain.com/p/job_title",
      valueType: "keyword",
    },
    mobile_phone: {
      name: "mobile_phone",
      iri: "https://littlebigbrain.com/p/mobile_phone",
      valueType: "keyword",
    },
    company_name: {
      name: "company_name",
      iri: "https://littlebigbrain.com/p/company_name",
      valueType: "keyword",
    },
    lead_status: {
      name: "lead_status",
      iri: "https://littlebigbrain.com/p/lead_status",
      valueType: "keyword",
    },
    is_active: {
      name: "is_active",
      iri: "https://littlebigbrain.com/p/is_active",
      valueType: "bool",
    },
    source_user_id: {
      name: "source_user_id",
      iri: "https://littlebigbrain.com/p/source_user_id",
      valueType: "keyword",
    },
    file_extension: {
      name: "file_extension",
      iri: "https://littlebigbrain.com/p/file_extension",
      valueType: "keyword",
    },
    mime_type: {
      name: "mime_type",
      iri: "https://littlebigbrain.com/p/mime_type",
      valueType: "keyword",
    },
    size_bytes: {
      name: "size_bytes",
      iri: "https://littlebigbrain.com/p/size_bytes",
      valueType: "i64",
    },
    content_hash: {
      name: "content_hash",
      iri: "https://littlebigbrain.com/p/content_hash",
      valueType: "keyword",
    },
    version_label: {
      name: "version_label",
      iri: "https://littlebigbrain.com/p/version_label",
      valueType: "keyword",
    },
    document_type: {
      name: "document_type",
      iri: "https://littlebigbrain.com/p/document_type",
      valueType: "keyword",
    },
    language: {
      name: "language",
      iri: "https://littlebigbrain.com/p/language",
      valueType: "keyword",
    },
    page_count: {
      name: "page_count",
      iri: "https://littlebigbrain.com/p/page_count",
      valueType: "i64",
    },
    path: {
      name: "path",
      iri: "https://littlebigbrain.com/p/path",
      valueType: "keyword",
    },
    sensitivity_label: {
      name: "sensitivity_label",
      iri: "https://littlebigbrain.com/p/sensitivity_label",
      valueType: "keyword",
    },
    item_count: {
      name: "item_count",
      iri: "https://littlebigbrain.com/p/item_count",
      valueType: "i64",
    },
  },
  relations: {
    IN_SITE: {
      name: "IN_SITE",
      iri: "https://littlebigbrain.com/r/in_site",
      domain: ["Library", "Page"],
      range: ["Site"],
      cardinality: "many_to_one",
      inverse: "SITE_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/site_holds",
    },
    IN_LIBRARY: {
      name: "IN_LIBRARY",
      iri: "https://littlebigbrain.com/r/in_library",
      domain: ["Folder", "Document"],
      range: ["Library"],
      cardinality: "many_to_one",
      inverse: "LIBRARY_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/library_holds",
    },
    IN_FOLDER: {
      name: "IN_FOLDER",
      iri: "https://littlebigbrain.com/r/in_folder",
      domain: ["Folder", "Document"],
      range: ["Folder"],
      cardinality: "many_to_one",
      inverse: "FOLDER_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/folder_holds",
    },
    CREATED_BY: {
      name: "CREATED_BY",
      iri: "https://littlebigbrain.com/r/created_by",
      domain: ["Document", "Folder"],
      range: ["User"],
      cardinality: "many_to_one",
      inverse: "CREATOR_OF",
      inverseIri: "https://littlebigbrain.com/r/creator_of",
    },
    MODIFIED_BY: {
      name: "MODIFIED_BY",
      iri: "https://littlebigbrain.com/r/modified_by",
      domain: ["Document", "Folder"],
      range: ["User"],
      cardinality: "many_to_one",
      inverse: "LAST_MODIFIED",
      inverseIri: "https://littlebigbrain.com/r/last_modified",
    },
    TAGGED_WITH: {
      name: "TAGGED_WITH",
      iri: "https://littlebigbrain.com/r/tagged_with",
      domain: ["Document"],
      range: ["Tag"],
      cardinality: "many_to_many",
      inverse: "TAGS",
      inverseIri: "https://littlebigbrain.com/r/tags",
    },
    BROADER: {
      name: "BROADER",
      iri: "https://littlebigbrain.com/r/broader",
      domain: ["Tag"],
      range: ["Tag"],
      cardinality: "many_to_many",
      inverse: "NARROWER",
      inverseIri: "https://littlebigbrain.com/r/narrower",
    },
    LINKS_TO: {
      name: "LINKS_TO",
      iri: "https://littlebigbrain.com/r/links_to",
      domain: ["Document"],
      range: ["Document"],
      cardinality: "many_to_many",
      inverse: "LINKED_FROM",
      inverseIri: "https://littlebigbrain.com/r/linked_from",
    },
  },
  questions: [
    {
      id: "doc-01",
      text: "Which documents are in a folder, and how big are they?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?folder ?document ?size_bytes ?file_extension WHERE {\n  # Input: a folder's name. UNDEF answers for every folder.\n  VALUES ?folder { UNDEF }\n  ?f a/rdfs:subClassOf* c:folder ;\n     rdfs:label ?folder .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_folder ?f ;\n     rdfs:label ?document .\n  OPTIONAL { ?d p:size_bytes ?size_bytes }\n  OPTIONAL { ?d p:file_extension ?file_extension }\n}\nORDER BY ?folder DESC(?size_bytes)\n",
    },
    {
      id: "doc-02",
      text: "Which documents in a library changed last week, and who changed them?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?library ?document ?modified_at ?modified_by WHERE {\n  # Inputs: a library's name, and the start of the window (a week ago) as\n  # xsd:dateTime. UNDEF answers for every library or date.\n  VALUES (?library ?since) { (UNDEF UNDEF) }\n  ?l a/rdfs:subClassOf* c:library ;\n     rdfs:label ?library .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_library ?l ;\n     rdfs:label ?document ;\n     p:modified_at ?modified_at .\n  FILTER(!BOUND(?since) || ?modified_at >= ?since)\n  OPTIONAL {\n    ?d r:modified_by ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?modified_by .\n  }\n}\nORDER BY ?library DESC(?modified_at)\n",
    },
    {
      id: "doc-03",
      text: "Who created a document, and when?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document ?created_at ?created_by WHERE {\n  # Input: a document's name. UNDEF answers for every document.\n  VALUES ?document { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document .\n  OPTIONAL { ?d p:created_at ?created_at }\n  OPTIONAL {\n    ?d r:created_by ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?created_by .\n  }\n}\nORDER BY ?document\n",
    },
    {
      id: "doc-04",
      text: "Which libraries and pages does a site hold?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?site ?kind ?item WHERE {\n  # Input: a site\'s name. UNDEF answers for every site.\n  VALUES ?site { UNDEF }\n  ?s a/rdfs:subClassOf* c:site ;\n     rdfs:label ?site .\n  ?x r:in_site ?s ;\n     rdfs:label ?item .\n  { ?x a/rdfs:subClassOf* c:library BIND("library" AS ?kind) }\n  UNION\n  { ?x a/rdfs:subClassOf* c:page BIND("page" AS ?kind) }\n}\nORDER BY ?site ?kind ?item\n',
    },
    {
      id: "doc-05",
      text: "Where is a document: its folders up to its library and site?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document ?path ?folder ?library ?site WHERE {\n  # Input: a document's name. UNDEF answers for every document.\n  VALUES ?document { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document .\n  OPTIONAL { ?d p:path ?path }\n  # Every folder up the path: one or more IN_FOLDER steps.\n  OPTIONAL {\n    ?d r:in_folder+ ?f .\n    ?f a/rdfs:subClassOf* c:folder ;\n       rdfs:label ?folder .\n  }\n  OPTIONAL {\n    ?d r:in_library ?l .\n    ?l a/rdfs:subClassOf* c:library ;\n       rdfs:label ?library .\n    OPTIONAL {\n      ?l r:in_site ?s .\n      ?s a/rdfs:subClassOf* c:site ;\n         rdfs:label ?site .\n    }\n  }\n}\nORDER BY ?document ?folder\n",
    },
    {
      id: "doc-06",
      text: "Which documents carry a tag, or a narrower tag?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?tag ?document ?tagged_with WHERE {\n  # Input: a tag's name. UNDEF answers for every tag.\n  VALUES ?tag { UNDEF }\n  ?t a/rdfs:subClassOf* c:tag ;\n     rdfs:label ?tag .\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     r:tagged_with ?direct .\n  # The tag itself or a narrower one: zero or more BROADER steps.\n  ?direct r:broader* ?t ;\n          rdfs:label ?tagged_with .\n}\nORDER BY ?tag ?document\n",
    },
    {
      id: "doc-07",
      text: "Which documents are of a given type, such as contracts or policies?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document_type ?document WHERE {\n  # Input: a document type, such as Contract. UNDEF answers for every type.\n  VALUES ?document_type { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:document_type ?document_type .\n}\nORDER BY ?document_type ?document\n",
    },
    {
      id: "doc-08",
      text: "Which documents may a given person or group read?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT DISTINCT ?document ?principal WHERE {\n  # Input: the principals of a person or a group as the source writes them:\n  # a user's own principal and those of its groups. UNDEF lists every reader.\n  VALUES ?principal { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:acl ?principal .\n}\nORDER BY ?document ?principal\n",
    },
    {
      id: "doc-09",
      text: "Which documents link to a given document?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?target ?document WHERE {\n  # Input: the linked document's name. UNDEF answers for every document.\n  VALUES ?target { UNDEF }\n  ?t a/rdfs:subClassOf* c:document ;\n     rdfs:label ?target .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:links_to ?t ;\n     rdfs:label ?document .\n}\nORDER BY ?target ?document\n",
    },
    {
      id: "doc-10",
      text: "Which documents carry a sensitivity label, such as Confidential?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?sensitivity_label ?document WHERE {\n  # Input: a sensitivity label, such as Confidential. UNDEF answers for\n  # every label.\n  VALUES ?sensitivity_label { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:sensitivity_label ?sensitivity_label .\n}\nORDER BY ?sensitivity_label ?document\n",
    },
    {
      id: "doc-11",
      text: "Which documents have the same content in more than one place?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?content_hash ?document ?path WHERE {\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:content_hash ?content_hash .\n  OPTIONAL { ?d p:path ?path }\n  {\n    SELECT ?content_hash WHERE {\n      ?x a/rdfs:subClassOf* c:document ;\n         p:content_hash ?content_hash .\n    }\n    GROUP BY ?content_hash\n    HAVING (COUNT(?x) > 1)\n  }\n}\nORDER BY ?content_hash ?path\n",
    },
    {
      id: "doc-12",
      text: "Which users changed the most documents in a library this month?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?library ?user (COUNT(?d) AS ?documents_changed) WHERE {\n  # Input: a library's name. UNDEF answers for every library.\n  VALUES ?library { UNDEF }\n  ?l a/rdfs:subClassOf* c:library ;\n     rdfs:label ?library .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_library ?l ;\n     p:modified_at ?modified_at ;\n     r:modified_by ?u .\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  # This month: the year and the month of today.\n  FILTER(YEAR(?modified_at) = YEAR(NOW()) && MONTH(?modified_at) = MONTH(NOW()))\n}\nGROUP BY ?library ?user\nORDER BY ?library DESC(?documents_changed) ?user\n",
    },
    {
      id: "doc-13",
      text: "What file types does a library hold, by count and size?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?library ?file_extension ?mime_type (COUNT(?d) AS ?documents) (SUM(?size) AS ?size_bytes) WHERE {\n  ?d a/rdfs:subClassOf* c:document ;\n     r:in_library ?l ;\n     p:file_extension ?file_extension .\n  OPTIONAL { ?d p:mime_type ?mime_type }\n  OPTIONAL { ?d p:size_bytes ?size }\n  ?l a/rdfs:subClassOf* c:library ;\n     rdfs:label ?library .\n}\nGROUP BY ?library ?file_extension ?mime_type\nORDER BY ?library ?file_extension\n",
    },
    {
      id: "doc-14",
      text: "Which documents are in a language, with how many pages?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?language ?document ?page_count WHERE {\n  # Input: a language as a BCP 47 tag, such as de. UNDEF answers for every\n  # language.\n  VALUES ?language { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:language ?language .\n  OPTIONAL { ?d p:page_count ?page_count }\n}\nORDER BY ?language ?document\n",
    },
    {
      id: "doc-15",
      text: "Where does a document come from: which system, which id, which link, which version?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?document ?source_system ?source_id ?source_url ?version_label WHERE {\n  # Input: a document's name. UNDEF answers for every document.\n  VALUES ?document { UNDEF }\n  ?d a/rdfs:subClassOf* c:document ;\n     rdfs:label ?document ;\n     p:source_system ?source_system .\n  OPTIONAL { ?d p:source_id ?source_id }\n  OPTIONAL { ?d p:source_url ?source_url }\n  OPTIONAL { ?d p:version_label ?version_label }\n}\nORDER BY ?document\n",
    },
    {
      id: "doc-16",
      text: "Which people wrote documents in a site, and who are they?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT DISTINCT ?site ?person ?email ?job_title WHERE {\n  # Input: a site's name. UNDEF answers for every site.\n  VALUES ?site { UNDEF }\n  ?s a/rdfs:subClassOf* c:site ;\n     rdfs:label ?site .\n  ?d a/rdfs:subClassOf* c:document ;\n     r:created_by ?x .\n  # A file is in a library of the site; a page is in the site.\n  { ?d r:in_library/r:in_site ?s } UNION { ?d r:in_site ?s }\n  ?x a/rdfs:subClassOf* c:person ;\n     rdfs:label ?person .\n  OPTIONAL { ?x p:email ?email }\n  OPTIONAL { ?x p:job_title ?job_title }\n}\nORDER BY ?site ?person\n",
    },
  ],
} as const satisfies StarterTerms;

/** The Work management starter 1.1.0. */
export const work = {
  id: "work",
  version: "1.1.0",
  label: "Work management",
  classes: {
    Party: {
      name: "Party",
      iri: "https://littlebigbrain.com/class/party",
      superTypes: [],
    },
    Organization: {
      name: "Organization",
      iri: "https://littlebigbrain.com/class/organization",
      superTypes: ["Party"],
    },
    Person: {
      name: "Person",
      iri: "https://littlebigbrain.com/class/person",
      superTypes: ["Party"],
    },
    User: {
      name: "User",
      iri: "https://littlebigbrain.com/class/user",
      superTypes: ["Person"],
    },
    Team: {
      name: "Team",
      iri: "https://littlebigbrain.com/class/team",
      superTypes: [],
    },
    Task: {
      name: "Task",
      iri: "https://littlebigbrain.com/class/task",
      superTypes: [],
    },
    Pipeline: {
      name: "Pipeline",
      iri: "https://littlebigbrain.com/class/pipeline",
      superTypes: [],
    },
    Stage: {
      name: "Stage",
      iri: "https://littlebigbrain.com/class/stage",
      superTypes: [],
    },
    Tag: {
      name: "Tag",
      iri: "https://littlebigbrain.com/class/tag",
      superTypes: [],
    },
    Issue: {
      name: "Issue",
      iri: "https://littlebigbrain.com/class/issue",
      superTypes: ["Task"],
    },
    Project: {
      name: "Project",
      iri: "https://littlebigbrain.com/class/project",
      superTypes: [],
    },
    Milestone: {
      name: "Milestone",
      iri: "https://littlebigbrain.com/class/milestone",
      superTypes: [],
    },
    Iteration: {
      name: "Iteration",
      iri: "https://littlebigbrain.com/class/iteration",
      superTypes: [],
    },
    Comment: {
      name: "Comment",
      iri: "https://littlebigbrain.com/class/comment",
      superTypes: [],
    },
  },
  properties: {
    source_system: {
      name: "source_system",
      iri: "https://littlebigbrain.com/p/source_system",
      valueType: "keyword",
    },
    source_id: {
      name: "source_id",
      iri: "https://littlebigbrain.com/p/source_id",
      valueType: "keyword",
    },
    source_url: {
      name: "source_url",
      iri: "https://littlebigbrain.com/p/source_url",
      valueType: "keyword",
    },
    source_updated_at: {
      name: "source_updated_at",
      iri: "https://littlebigbrain.com/p/source_updated_at",
      valueType: "date_time",
    },
    source_key: {
      name: "source_key",
      iri: "https://littlebigbrain.com/p/source_key",
      valueType: "keyword",
    },
    text: {
      name: "text",
      iri: "https://littlebigbrain.com/p/text",
      valueType: "text",
    },
    acl: {
      name: "acl",
      iri: "https://littlebigbrain.com/p/acl",
      valueType: "keyword_set",
    },
    created_at: {
      name: "created_at",
      iri: "https://littlebigbrain.com/p/created_at",
      valueType: "date_time",
    },
    modified_at: {
      name: "modified_at",
      iri: "https://littlebigbrain.com/p/modified_at",
      valueType: "date_time",
    },
    description: {
      name: "description",
      iri: "https://littlebigbrain.com/p/description",
      valueType: "text",
    },
    phone: {
      name: "phone",
      iri: "https://littlebigbrain.com/p/phone",
      valueType: "keyword",
    },
    website: {
      name: "website",
      iri: "https://littlebigbrain.com/p/website",
      valueType: "keyword",
    },
    street_address: {
      name: "street_address",
      iri: "https://littlebigbrain.com/p/street_address",
      valueType: "keyword",
    },
    city: {
      name: "city",
      iri: "https://littlebigbrain.com/p/city",
      valueType: "keyword",
    },
    region: {
      name: "region",
      iri: "https://littlebigbrain.com/p/region",
      valueType: "keyword",
    },
    postal_code: {
      name: "postal_code",
      iri: "https://littlebigbrain.com/p/postal_code",
      valueType: "keyword",
    },
    country: {
      name: "country",
      iri: "https://littlebigbrain.com/p/country",
      valueType: "keyword",
    },
    linkedin_url: {
      name: "linkedin_url",
      iri: "https://littlebigbrain.com/p/linkedin_url",
      valueType: "keyword",
    },
    lifecycle_stage: {
      name: "lifecycle_stage",
      iri: "https://littlebigbrain.com/p/lifecycle_stage",
      valueType: "keyword",
    },
    domain: {
      name: "domain",
      iri: "https://littlebigbrain.com/p/domain",
      valueType: "keyword",
    },
    industry: {
      name: "industry",
      iri: "https://littlebigbrain.com/p/industry",
      valueType: "keyword",
    },
    annual_revenue: {
      name: "annual_revenue",
      iri: "https://littlebigbrain.com/p/annual_revenue",
      valueType: "f64",
    },
    employee_count: {
      name: "employee_count",
      iri: "https://littlebigbrain.com/p/employee_count",
      valueType: "i64",
    },
    company_type: {
      name: "company_type",
      iri: "https://littlebigbrain.com/p/company_type",
      valueType: "keyword",
    },
    first_name: {
      name: "first_name",
      iri: "https://littlebigbrain.com/p/first_name",
      valueType: "keyword",
    },
    last_name: {
      name: "last_name",
      iri: "https://littlebigbrain.com/p/last_name",
      valueType: "keyword",
    },
    email: {
      name: "email",
      iri: "https://littlebigbrain.com/p/email",
      valueType: "keyword",
    },
    job_title: {
      name: "job_title",
      iri: "https://littlebigbrain.com/p/job_title",
      valueType: "keyword",
    },
    mobile_phone: {
      name: "mobile_phone",
      iri: "https://littlebigbrain.com/p/mobile_phone",
      valueType: "keyword",
    },
    company_name: {
      name: "company_name",
      iri: "https://littlebigbrain.com/p/company_name",
      valueType: "keyword",
    },
    lead_status: {
      name: "lead_status",
      iri: "https://littlebigbrain.com/p/lead_status",
      valueType: "keyword",
    },
    is_active: {
      name: "is_active",
      iri: "https://littlebigbrain.com/p/is_active",
      valueType: "bool",
    },
    source_user_id: {
      name: "source_user_id",
      iri: "https://littlebigbrain.com/p/source_user_id",
      valueType: "keyword",
    },
    probability: {
      name: "probability",
      iri: "https://littlebigbrain.com/p/probability",
      valueType: "f64",
    },
    is_closed: {
      name: "is_closed",
      iri: "https://littlebigbrain.com/p/is_closed",
      valueType: "bool",
    },
    is_won: {
      name: "is_won",
      iri: "https://littlebigbrain.com/p/is_won",
      valueType: "bool",
    },
    object_type: {
      name: "object_type",
      iri: "https://littlebigbrain.com/p/object_type",
      valueType: "keyword",
    },
    display_order: {
      name: "display_order",
      iri: "https://littlebigbrain.com/p/display_order",
      valueType: "i64",
    },
    stage_category: {
      name: "stage_category",
      iri: "https://littlebigbrain.com/p/stage_category",
      valueType: "keyword",
    },
    priority: {
      name: "priority",
      iri: "https://littlebigbrain.com/p/priority",
      valueType: "keyword",
    },
    status: {
      name: "status",
      iri: "https://littlebigbrain.com/p/status",
      valueType: "keyword",
    },
    start_at: {
      name: "start_at",
      iri: "https://littlebigbrain.com/p/start_at",
      valueType: "date_time",
    },
    end_at: {
      name: "end_at",
      iri: "https://littlebigbrain.com/p/end_at",
      valueType: "date_time",
    },
    due_at: {
      name: "due_at",
      iri: "https://littlebigbrain.com/p/due_at",
      valueType: "date_time",
    },
    completed_at: {
      name: "completed_at",
      iri: "https://littlebigbrain.com/p/completed_at",
      valueType: "date_time",
    },
    identifier: {
      name: "identifier",
      iri: "https://littlebigbrain.com/p/identifier",
      valueType: "keyword",
    },
    issue_type: {
      name: "issue_type",
      iri: "https://littlebigbrain.com/p/issue_type",
      valueType: "keyword",
    },
    estimate: {
      name: "estimate",
      iri: "https://littlebigbrain.com/p/estimate",
      valueType: "f64",
    },
    started_at: {
      name: "started_at",
      iri: "https://littlebigbrain.com/p/started_at",
      valueType: "date_time",
    },
    canceled_at: {
      name: "canceled_at",
      iri: "https://littlebigbrain.com/p/canceled_at",
      valueType: "date_time",
    },
    target_date: {
      name: "target_date",
      iri: "https://littlebigbrain.com/p/target_date",
      valueType: "date_time",
    },
    progress: {
      name: "progress",
      iri: "https://littlebigbrain.com/p/progress",
      valueType: "f64",
    },
    health: {
      name: "health",
      iri: "https://littlebigbrain.com/p/health",
      valueType: "keyword",
    },
    number: {
      name: "number",
      iri: "https://littlebigbrain.com/p/number",
      valueType: "i64",
    },
  },
  relations: {
    ASSIGNED_TO: {
      name: "ASSIGNED_TO",
      iri: "https://littlebigbrain.com/r/assigned_to",
      domain: ["Task"],
      range: ["User"],
      cardinality: "many_to_one",
      inverse: "ASSIGNEE_OF",
      inverseIri: "https://littlebigbrain.com/r/assignee_of",
    },
    CREATED_BY: {
      name: "CREATED_BY",
      iri: "https://littlebigbrain.com/r/created_by",
      domain: ["Task", "Comment"],
      range: ["User"],
      cardinality: "many_to_one",
      inverse: "CREATOR_OF",
      inverseIri: "https://littlebigbrain.com/r/creator_of",
    },
    MEMBER_OF: {
      name: "MEMBER_OF",
      iri: "https://littlebigbrain.com/r/member_of",
      domain: ["User"],
      range: ["Team"],
      cardinality: "many_to_many",
      inverse: "HAS_MEMBER",
      inverseIri: "https://littlebigbrain.com/r/has_member",
    },
    IN_STAGE: {
      name: "IN_STAGE",
      iri: "https://littlebigbrain.com/r/in_stage",
      domain: ["Task"],
      range: ["Stage"],
      cardinality: "many_to_one",
      inverse: "STAGE_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/stage_holds",
    },
    IN_PIPELINE: {
      name: "IN_PIPELINE",
      iri: "https://littlebigbrain.com/r/in_pipeline",
      domain: ["Stage"],
      range: ["Pipeline"],
      cardinality: "many_to_one",
      inverse: "PIPELINE_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/pipeline_holds",
    },
    TAGGED_WITH: {
      name: "TAGGED_WITH",
      iri: "https://littlebigbrain.com/r/tagged_with",
      domain: ["Task"],
      range: ["Tag"],
      cardinality: "many_to_many",
      inverse: "TAGS",
      inverseIri: "https://littlebigbrain.com/r/tags",
    },
    BROADER: {
      name: "BROADER",
      iri: "https://littlebigbrain.com/r/broader",
      domain: ["Tag"],
      range: ["Tag"],
      cardinality: "many_to_many",
      inverse: "NARROWER",
      inverseIri: "https://littlebigbrain.com/r/narrower",
    },
    FOR_ORGANIZATION: {
      name: "FOR_ORGANIZATION",
      iri: "https://littlebigbrain.com/r/for_organization",
      domain: ["Issue"],
      range: ["Organization"],
      cardinality: "many_to_many",
      inverse: "ORGANIZATION_OF",
      inverseIri: "https://littlebigbrain.com/r/organization_of",
    },
    IN_TEAM: {
      name: "IN_TEAM",
      iri: "https://littlebigbrain.com/r/in_team",
      domain: ["Task", "Project", "Pipeline", "Iteration"],
      range: ["Team"],
      cardinality: "many_to_many",
      inverse: "TEAM_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/team_holds",
    },
    IN_PROJECT: {
      name: "IN_PROJECT",
      iri: "https://littlebigbrain.com/r/in_project",
      domain: ["Task"],
      range: ["Project"],
      cardinality: "many_to_one",
      inverse: "PROJECT_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/project_holds",
    },
    IN_MILESTONE: {
      name: "IN_MILESTONE",
      iri: "https://littlebigbrain.com/r/in_milestone",
      domain: ["Task"],
      range: ["Milestone"],
      cardinality: "many_to_one",
      inverse: "MILESTONE_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/milestone_holds",
    },
    MILESTONE_OF: {
      name: "MILESTONE_OF",
      iri: "https://littlebigbrain.com/r/milestone_of",
      domain: ["Milestone"],
      range: ["Project"],
      cardinality: "many_to_one",
      inverse: "HAS_MILESTONE",
      inverseIri: "https://littlebigbrain.com/r/has_milestone",
    },
    IN_ITERATION: {
      name: "IN_ITERATION",
      iri: "https://littlebigbrain.com/r/in_iteration",
      domain: ["Task"],
      range: ["Iteration"],
      cardinality: "many_to_one",
      inverse: "ITERATION_HOLDS",
      inverseIri: "https://littlebigbrain.com/r/iteration_holds",
    },
    LED_BY: {
      name: "LED_BY",
      iri: "https://littlebigbrain.com/r/led_by",
      domain: ["Project"],
      range: ["User"],
      cardinality: "many_to_one",
      inverse: "LEADS",
      inverseIri: "https://littlebigbrain.com/r/leads",
    },
    SUBTASK_OF: {
      name: "SUBTASK_OF",
      iri: "https://littlebigbrain.com/r/subtask_of",
      domain: ["Task"],
      range: ["Task"],
      cardinality: "many_to_one",
      inverse: "HAS_SUBTASK",
      inverseIri: "https://littlebigbrain.com/r/has_subtask",
    },
    BLOCKS: {
      name: "BLOCKS",
      iri: "https://littlebigbrain.com/r/blocks",
      domain: ["Task"],
      range: ["Task"],
      cardinality: "many_to_many",
      inverse: "BLOCKED_BY",
      inverseIri: "https://littlebigbrain.com/r/blocked_by",
    },
    RELATED_TO: {
      name: "RELATED_TO",
      iri: "https://littlebigbrain.com/r/related_to",
      domain: ["Task"],
      range: ["Task"],
      cardinality: "many_to_many",
      inverse: null,
      inverseIri: null,
    },
    DUPLICATE_OF: {
      name: "DUPLICATE_OF",
      iri: "https://littlebigbrain.com/r/duplicate_of",
      domain: ["Task"],
      range: ["Task"],
      cardinality: "many_to_one",
      inverse: "HAS_DUPLICATE",
      inverseIri: "https://littlebigbrain.com/r/has_duplicate",
    },
    COMMENT_ON: {
      name: "COMMENT_ON",
      iri: "https://littlebigbrain.com/r/comment_on",
      domain: ["Comment"],
      range: ["Task"],
      cardinality: "many_to_one",
      inverse: "HAS_COMMENT",
      inverseIri: "https://littlebigbrain.com/r/has_comment",
    },
  },
  questions: [
    {
      id: "work-01",
      text: "Which open issues does a team have, by stage and priority?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?issue ?stage ?stage_category ?priority WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_team ?t ;\n     rdfs:label ?issue ;\n     r:in_stage ?s .\n  ?s a/rdfs:subClassOf* c:stage ;\n     rdfs:label ?stage ;\n     p:is_closed false .\n  OPTIONAL { ?s p:stage_category ?stage_category }\n  OPTIONAL { ?i p:priority ?priority }\n}\nORDER BY ?team ?stage ?priority ?issue\n",
    },
    {
      id: "work-02",
      text: "What is assigned to a user, and what is overdue?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?user ?task ?due_at ?overdue WHERE {\n  # Input: a user's name. UNDEF answers for every user.\n  VALUES ?user { UNDEF }\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  ?t a/rdfs:subClassOf* c:task ;\n     r:assigned_to ?u ;\n     rdfs:label ?task .\n  FILTER NOT EXISTS { ?t p:completed_at ?completed_at }\n  FILTER NOT EXISTS { ?t p:canceled_at ?canceled_at }\n  OPTIONAL { ?t p:due_at ?due_at }\n  BIND(BOUND(?due_at) && ?due_at < NOW() AS ?overdue)\n}\nORDER BY ?user ?due_at\n",
    },
    {
      id: "work-03",
      text: "Which issues are in the current iteration, and how many are done?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?iteration ?issue ?stage_category ?issues ?done WHERE {\n  ?it a/rdfs:subClassOf* c:iteration ;\n      rdfs:label ?iteration ;\n      p:start_at ?start_at ;\n      p:end_at ?end_at .\n  # The current iteration: started and not ended.\n  FILTER(?start_at <= NOW() && ?end_at >= NOW())\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_iteration ?it ;\n     rdfs:label ?issue .\n  OPTIONAL {\n    ?i r:in_stage ?s .\n    ?s a/rdfs:subClassOf* c:stage ;\n       p:stage_category ?stage_category .\n  }\n  # How many issues the iteration holds, and how many are done.\n  {\n    SELECT ?it (COUNT(?j) AS ?issues)\n           (SUM(IF(COALESCE(?category, "") = "completed", 1, 0)) AS ?done) WHERE {\n      ?j a/rdfs:subClassOf* c:issue ;\n         r:in_iteration ?it .\n      OPTIONAL { ?j r:in_stage/p:stage_category ?category }\n    }\n    GROUP BY ?it\n  }\n}\nORDER BY ?iteration ?stage_category ?issue\n',
    },
    {
      id: "work-04",
      text: "Which tasks block a task, directly or indirectly?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?blocker ?status WHERE {\n  # Input: the blocked task's name. UNDEF answers for every task.\n  VALUES ?task { UNDEF }\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task .\n  # Directly or indirectly: one or more BLOCKS steps.\n  ?b r:blocks+ ?t ;\n     rdfs:label ?blocker .\n  OPTIONAL { ?b p:status ?status }\n}\nORDER BY ?task ?blocker\n",
    },
    {
      id: "work-05",
      text: "What is the progress and health of a project, and who leads it?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?project ?progress ?health ?target_date ?lead WHERE {\n  # Input: a project's name. UNDEF answers for every project.\n  VALUES ?project { UNDEF }\n  ?pr a/rdfs:subClassOf* c:project ;\n      rdfs:label ?project .\n  OPTIONAL { ?pr p:progress ?progress }\n  OPTIONAL { ?pr p:health ?health }\n  OPTIONAL { ?pr p:target_date ?target_date }\n  OPTIONAL {\n    ?pr r:led_by ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?lead .\n  }\n}\nORDER BY ?project\n",
    },
    {
      id: "work-06",
      text: "Which issues belong to a milestone of a project, and when is it due?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?project ?milestone ?target_date ?issue WHERE {\n  # Input: a project's name. UNDEF answers for every project.\n  VALUES ?project { UNDEF }\n  ?pr a/rdfs:subClassOf* c:project ;\n      rdfs:label ?project .\n  ?m a/rdfs:subClassOf* c:milestone ;\n     r:milestone_of ?pr ;\n     rdfs:label ?milestone .\n  OPTIONAL { ?m p:target_date ?target_date }\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_milestone ?m ;\n     rdfs:label ?issue .\n}\nORDER BY ?project ?target_date ?issue\n",
    },
    {
      id: "work-07",
      text: "Which sub-tasks does a task have, at any depth?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?subtask ?status WHERE {\n  # Input: the parent task's name. UNDEF answers for every task.\n  VALUES ?task { UNDEF }\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task .\n  # At any depth: one or more SUBTASK_OF steps.\n  ?s r:subtask_of+ ?t ;\n     rdfs:label ?subtask .\n  OPTIONAL { ?s p:status ?status }\n}\nORDER BY ?task ?subtask\n",
    },
    {
      id: "work-08",
      text: "Which issues carry a label, or a narrower label?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?label ?issue ?tagged_with WHERE {\n  # Input: a label's name. UNDEF answers for every label.\n  VALUES ?label { UNDEF }\n  ?t a/rdfs:subClassOf* c:tag ;\n     rdfs:label ?label .\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue ;\n     r:tagged_with ?direct .\n  # The label itself or a narrower one: zero or more BROADER steps.\n  ?direct r:broader* ?t ;\n          rdfs:label ?tagged_with .\n}\nORDER BY ?label ?issue\n",
    },
    {
      id: "work-09",
      text: "Which issues did a customer organization ask for?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?organization ?domain ?issue WHERE {\n  # Input: the organization's web domain. UNDEF answers for every\n  # organization.\n  VALUES ?domain { UNDEF }\n  ?o a/rdfs:subClassOf* c:organization ;\n     rdfs:label ?organization ;\n     p:domain ?domain .\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:for_organization ?o ;\n     rdfs:label ?issue .\n}\nORDER BY ?organization ?issue\n",
    },
    {
      id: "work-10",
      text: "What did a user create or comment on this week?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT ?user ?action ?item ?created_at WHERE {\n  # Inputs: a user\'s name, and the start of the week as xsd:dateTime. UNDEF\n  # answers for every user or date.\n  VALUES (?user ?since) { (UNDEF UNDEF) }\n  ?u a/rdfs:subClassOf* c:user ;\n     rdfs:label ?user .\n  {\n    ?t a/rdfs:subClassOf* c:task ;\n       r:created_by ?u ;\n       rdfs:label ?item ;\n       p:created_at ?created_at .\n    BIND("created" AS ?action)\n  } UNION {\n    ?k a/rdfs:subClassOf* c:comment ;\n       r:created_by ?u ;\n       r:comment_on ?t ;\n       p:created_at ?created_at .\n    ?t rdfs:label ?item .\n    BIND("commented on" AS ?action)\n  }\n  FILTER(!BOUND(?since) || ?created_at >= ?since)\n}\nORDER BY ?user DESC(?created_at)\n',
    },
    {
      id: "work-11",
      text: "How long do issues take from start to completion, per team?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?issue ?started_at ?completed_at WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  # The time an issue took is completed_at minus started_at: the data plane\n  # does not subtract date-times yet, so the query returns both.\n  ?i a/rdfs:subClassOf* c:issue ;\n     r:in_team ?t ;\n     rdfs:label ?issue ;\n     p:started_at ?started_at ;\n     p:completed_at ?completed_at .\n}\nORDER BY ?team ?completed_at\n",
    },
    {
      id: "work-12",
      text: "Which tasks repeat or relate to a given task?",
      sparql:
        'PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?task ?link ?other WHERE {\n  # Input: a task\'s name. UNDEF answers for every task.\n  VALUES ?task { UNDEF }\n  ?t a/rdfs:subClassOf* c:task ;\n     rdfs:label ?task .\n  { ?x r:duplicate_of ?t . BIND("duplicate" AS ?link) }\n  UNION\n  { ?t r:duplicate_of ?x . BIND("original" AS ?link) }\n  UNION\n  # RELATED_TO is symmetric: the graph holds both directions.\n  { ?t r:related_to ?x . BIND("related" AS ?link) }\n  ?x rdfs:label ?other .\n}\nORDER BY ?task ?link ?other\n',
    },
    {
      id: "work-13",
      text: "Which open issues have no assignee or no estimate?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?issue ?no_assignee ?no_estimate WHERE {\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue .\n  # Open: not in a closed stage.\n  FILTER NOT EXISTS { ?i r:in_stage/p:is_closed true }\n  BIND(NOT EXISTS { ?i r:assigned_to ?u } AS ?no_assignee)\n  BIND(NOT EXISTS { ?i p:estimate ?e } AS ?no_estimate)\n  FILTER(?no_assignee || ?no_estimate)\n}\nORDER BY ?issue\n",
    },
    {
      id: "work-14",
      text: "Who are the members of a team?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?member ?email WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  ?u a/rdfs:subClassOf* c:user ;\n     r:member_of ?t ;\n     rdfs:label ?member .\n  OPTIONAL { ?u p:email ?email }\n}\nORDER BY ?team ?member\n",
    },
    {
      id: "work-15",
      text: "What are a team's workflow stages, in order?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?team ?pipeline ?display_order ?stage ?stage_category WHERE {\n  # Input: a team's name. UNDEF answers for every team.\n  VALUES ?team { UNDEF }\n  ?t a/rdfs:subClassOf* c:team ;\n     rdfs:label ?team .\n  ?pl a/rdfs:subClassOf* c:pipeline ;\n      r:in_team ?t ;\n      rdfs:label ?pipeline .\n  ?s a/rdfs:subClassOf* c:stage ;\n     r:in_pipeline ?pl ;\n     rdfs:label ?stage .\n  OPTIONAL { ?s p:display_order ?display_order }\n  OPTIONAL { ?s p:stage_category ?stage_category }\n}\nORDER BY ?team ?pipeline ?display_order\n",
    },
    {
      id: "work-16",
      text: "Where does an issue come from: which system, which id, which link?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?issue ?identifier ?source_system ?source_id ?source_url WHERE {\n  # Input: the issue's identifier, such as ENG-123. UNDEF answers for every\n  # issue.\n  VALUES ?identifier { UNDEF }\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue ;\n     p:identifier ?identifier .\n  OPTIONAL { ?i p:source_system ?source_system }\n  OPTIONAL { ?i p:source_id ?source_id }\n  OPTIONAL { ?i p:source_url ?source_url }\n}\nORDER BY ?identifier\n",
    },
    {
      id: "work-17",
      text: "Which issues were canceled, and of what type?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?issue ?issue_type ?canceled_at WHERE {\n  ?i a/rdfs:subClassOf* c:issue ;\n     rdfs:label ?issue ;\n     p:canceled_at ?canceled_at .\n  OPTIONAL { ?i p:issue_type ?issue_type }\n}\nORDER BY DESC(?canceled_at)\n",
    },
    {
      id: "work-18",
      text: "Which open tasks remain in a project, and who does them?",
      sparql:
        "PREFIX c: <https://littlebigbrain.com/class/>\nPREFIX p: <https://littlebigbrain.com/p/>\nPREFIX r: <https://littlebigbrain.com/r/>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n\nSELECT ?project ?task ?due_at ?assignee WHERE {\n  # Input: a project's name. UNDEF answers for every project.\n  VALUES ?project { UNDEF }\n  ?pr a/rdfs:subClassOf* c:project ;\n      rdfs:label ?project .\n  ?t a/rdfs:subClassOf* c:task ;\n     r:in_project ?pr ;\n     rdfs:label ?task .\n  FILTER NOT EXISTS { ?t p:completed_at ?completed_at }\n  FILTER NOT EXISTS { ?t p:canceled_at ?canceled_at }\n  FILTER NOT EXISTS { ?t r:in_stage/p:is_closed true }\n  OPTIONAL { ?t p:due_at ?due_at }\n  OPTIONAL {\n    ?t r:assigned_to ?u .\n    ?u a/rdfs:subClassOf* c:user ;\n       rdfs:label ?assignee .\n  }\n}\nORDER BY ?project ?due_at ?task\n",
    },
  ],
} as const satisfies StarterTerms;
